// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv5-Ou_EgDOihndSfW1G59vdsWFtmjnmE',
    appId: '1:959776568833:web:9594c8d75799de990bb200',
    messagingSenderId: '959776568833',
    projectId: 'flutter-firebase-demo-4a945',
    authDomain: 'flutter-firebase-demo-4a945.firebaseapp.com',
    storageBucket: 'flutter-firebase-demo-4a945.firebasestorage.app',
    measurementId: 'G-C4JYBD1BDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3lZsyf8n1PpwJEow1x8aNnVNbTBQUH_8',
    appId: '1:959776568833:android:f245cc6abd7ac17b0bb200',
    messagingSenderId: '959776568833',
    projectId: 'flutter-firebase-demo-4a945',
    storageBucket: 'flutter-firebase-demo-4a945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRsdD4sbdbqcUmCMmfMzr-56dP56rJmVk',
    appId: '1:959776568833:ios:d1fa8622ea03750f0bb200',
    messagingSenderId: '959776568833',
    projectId: 'flutter-firebase-demo-4a945',
    storageBucket: 'flutter-firebase-demo-4a945.firebasestorage.app',
    iosBundleId: 'com.example.profileDemoAppWithFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRsdD4sbdbqcUmCMmfMzr-56dP56rJmVk',
    appId: '1:959776568833:ios:d1fa8622ea03750f0bb200',
    messagingSenderId: '959776568833',
    projectId: 'flutter-firebase-demo-4a945',
    storageBucket: 'flutter-firebase-demo-4a945.firebasestorage.app',
    iosBundleId: 'com.example.profileDemoAppWithFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv5-Ou_EgDOihndSfW1G59vdsWFtmjnmE',
    appId: '1:959776568833:web:498067408e7f6e020bb200',
    messagingSenderId: '959776568833',
    projectId: 'flutter-firebase-demo-4a945',
    authDomain: 'flutter-firebase-demo-4a945.firebaseapp.com',
    storageBucket: 'flutter-firebase-demo-4a945.firebasestorage.app',
    measurementId: 'G-Q9TF8R8TLZ',
  );
}
